services:
  1db:
    image: postgres:15
    container_name: mydb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=Html2090
      - POSTGRES_USER=odoo
    volumes:
      - ./${APP_Owner}-data:/var/lib/postgresql/data
    networks:
      - simple-odoo
      
  1odoo:
    image: odoo:17
    container_name: myodoo
    depends_on:
    - 1db
    ports:
    - "8169:8069"
    volumes:
      - ./${APP_Owner}-odoo-web-data:/var/lib/odoo:rw
      - ./${APP_Owner}-config:/etc/odoo:rw
      - ./${APP_Owner}-addons:/mnt/extra-addons:rw
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=Html2090
    networks:
      - simple-odoo

networks:
  simple-odoo: