services:
  1db:
    image: postgres:15
    container_name: mydb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_PASSWORD}
    volumes:
      - ./${APP_Owner}/data:/var/lib/postgresql/data
    networks:
      - simple-odoo
      
  1odoo:
    image: odoo:17
    container_name: myodoo
    depends_on:
    - 1db
    ports:
    - "8169:8069"
    volumes:
      - ./${APP_Owner}/odoo-web-data:/var/lib/odoo:rw
      - ./${APP_Owner}/config:/etc/odoo:rw
      - ./${APP_Owner}/addons:/mnt/extra-addons:rw
    environment:
    - HOST=mydb
    - USER=${POSTGRES_PASSWORD}
    - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - simple-odoo

networks:
  simple-odoo: