services:
  1db:
    image: ${DB_IMAGE}
    container_name: ${APP_Name}_mydb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./${APP_Name}/data:/var/lib/postgresql/data
    networks:
      - simple-odoo
      
  1odoo:
    image: ${Odoo_IMAGE}
    container_name: ${APP_Name}_myodoo
    user: "1002:1003"
    depends_on:
    - 1db
    ports:
    - "8090-8290:8069"
    volumes:
      - ./${APP_Name}/odoo-web-data:/var/lib/odoo:rw
      - ./${APP_Name}/config:/etc/odoo:rw
      - ./${APP_Name}/addons:/mnt/extra-addons:rw
    environment:
    - HOST=${APP_Name}_mydb
    - USER=${POSTGRES_USER}
    - PASSWORD=${POSTGRES_PASSWORD}
    command: >
      bash -c "
      if [ $(id -u) -eq 0 ]; then
        groupmod -g 1003 odoo &&
        usermod -u 1002 odoo
        fi"
    networks:
      - simple-odoo

networks:
  simple-odoo: